"""
SMT-LIB2 约束导出器
====================================================
• 将约束转换为可由 Z3/CVC5 直接读取的 S-表达式
• 支持 cardinality、value_restriction、range (min≤x≤max) 等
"""

from __future__ import annotations

from typing import Any, Dict, List

from utils.logger import get_logger

logger = get_logger(__name__)


class SmtEmitter:
    """
    用法:
    >>> emitter = SmtEmitter()
    >>> smt = emitter.build(constraint_nodes)
    >>> Path("out/constraints.smt2").write_text(smt, encoding="utf-8")
    """

    def __init__(self) -> None:
        self.lines: List[str] = []

    # ------------ 主入口 ------------
    def build(self, constraints: List[Dict[str, Any]]) -> str:
        self.lines.append("; -------- Generated by kg_builder --------")
        for c in constraints:
            self._emit_constraint(c)
        smt = "\n".join(self.lines)
        logger.info("已生成 SMT-LIB2 约束：%d 行", len(self.lines))
        return smt

    # ------------ 私有 ------------
    def _emit_constraint(self, c: Dict[str, Any]) -> None:
        cid = c["cid"]
        expr = c["expression"]
        ctype = c["constraint_type"]

        match ctype:
            case "cardinality":
                # 假设 expression = "minOccurs=1,maxOccurs=1"
                min_occ = self._extract_int(expr, "minOccurs")
                max_occ = self._extract_int(expr, "maxOccurs")
                self.lines += [
                    f"; {cid}",
                    f"(assert (>= occurs_{cid} {min_occ}))",
                    f"(assert (<= occurs_{cid} {max_occ}))",
                ]
            case "value_restriction":
                self.lines += [f"; {cid}", f"(assert (= value_{cid} {c['value']}))"]
            case "format":
                # SMT 不擅长 regex；留待后处理
                self.lines += [f"; {cid} (regex check skipped)"]
            case _:
                self.lines += [f"; {cid} (unhandled type {ctype})"]

    @staticmethod
    def _extract_int(expr: str, key: str) -> int:
        import re

        m = re.search(rf"{key}\s*=\s*(\d+)", expr)
        return int(m.group(1)) if m else 0
