# Logging Configuration using dictConfig format

version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: "results/logs/app.log" # This path might be overridden by config.yaml
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  "": # Root logger
    level: DEBUG
    handlers: [console, file]
    propagate: yes
  # Example of specific logger configuration
  # src.llm_interaction:
  #   level: DEBUG
  #   handlers: [console, file]
  #   propagate: no # Prevent messages from bubbling up to the root logger